dist: focal
language: scala
jdk: openjdk17
scala:
  - 2.13.9
git:
  depth: false
before_install:
  - rvm reload
  - rvm install 3.1.2
before_cache:
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

services:
  - postgresql
  - redis-server
addons:
  postgresql: "12"
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.rvm
    - $HOME/.nvm
    - $HOME/.cache/coursier

before_script:
  - git config user.email "builds@travis-ci.com"
  - git config user.name "TravisCI"
  - psql -p 5433 -c "CREATE DATABASE ${DB_NAME} WITH OWNER = ${DB_USER};"
  - psql -p 5433 -c "ALTER USER ${DB_USER} PASSWORD '${DB_PASSWORD}';"

stages:
  - Compilation and OpenApi validation
  - Test Suite
  - publish_artifacts

jobs:
  include:
    - stage: Compilation and OpenApi validation
      name: "Compile & OpenApi validate"
      script:
       - sbt clean compile test:compile
       - bundle install
       - bundle exec hammertime lint doc/contracts/openapi.yaml
    - stage: Test Suite
      name: "Test Suite"
      script:
        - sbt 'runMain com.mdsol.mdr.Flyway; test'
    - stage: publish_artifacts
      name: "Publish Artifacts"
      if: type != pull_request AND branch = develop
      script: .travis/build.sh publish
